# Makes prompt a single line
[line_break]
disabled = false

# Show command duration
[cmd_duration]
format = "took [$duration]($style) "
min_time = 2_000  # Show command duration over 10,000 milliseconds (= 2 sec)

# These symbols will only show when battery levels are 20% or less
[battery]
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[[battery.display]]  # bold red style when capacity is between 0% and 20%
threshold = 20 
style = "bold red"

# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt
[character]                
success_symbol = "[ï—š](bold green)[ï—š](yellow)[ï—š](red)[ï—š](purple)"
error_symbol = "[âœ—](bold red) "
# success_symbol = "[âœ](bold green)"
# error_symbol = "[âœ—](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Git settings
[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

# setting hostname
[hostname]
ssh_only = false
format =  "[$hostname](bold red) [â†³](bold blue) " #ğŸ“‚ - file folder
trim_at = ".companyname.com"
disabled = false

# setting time display
[time]
disabled = false
format = 'ğŸ•™ [\[$time\]](bold yellow) '
time_format = "%T"

# setting username
[username]
style_user = "bold green"
style_root = "black bold"
format = "[$user]($style)[@](cyan)"
disabled = false
show_always = true

# display memory usage
# [memory_usage]
# disabled = false
# threshold = -1
# symbol = " "
# style = "bold dimmed green"
